### ISSUE TITLE
Doc Error

### ISSUE THREAD

**Issue by niallel** [lampaa/com.lampa.startapp#87]
The first example in the docs doesn't work:
`var sApp = startApp.set({
	"application":"com.application.name"
});`

application should be package like
`var sApp = startApp.set({
	"package":"com.application.name"
});`

Apart from that its a great plugin, many thanks.

**Comment by lampaa** [comment]
Hi, @niallel!
In the first case, the application starts like this:

```java
PackageManager manager = cordova.getActivity().getApplicationContext().getPackageManager();
LaunchIntent = manager.getLaunchIntentForPackage(params.getString("application"));
cordova.getActivity().startActivity(LaunchIntent);
```

In the second case, the application starts like this:
```java
LaunchIntent = new Intent();
LaunchIntent.setPackage(params.getString("package"));
cordova.getActivity().startActivity(LaunchIntent);
```

In the first case PackageManager find package and his start activity.
In the second case we added filter by package to Intent, view [Intent.setPackage()](https://developer.android.com/reference/android/content/Intent.html#setPackage(java.lang.String)).

**Comment by niallel** [comment]
Its strange, when I pass only "application" I get the following from the start error callback:

`ActivityNotFoundException: No Activity found to handle Intent {  }`

The Android log shows:

`W/System.err: android.content.ActivityNotFoundException: No Activity found to handle Intent {  }
W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1936)
W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)
W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4471)
W/System.err:     at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:342)
W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4429)
W/System.err:     at android.app.Activity.startActivity(Activity.java:4790)
W/System.err:     at android.app.Activity.startActivity(Activity.java:4758)
W/System.err:     at com.lampa.startapp.startApp.start(startApp.java:178)
W/System.err:     at com.lampa.startapp.startApp.execute(startApp.java:44)
W/System.err:     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)`

However when I just use "package" everything works fine.

**Comment by lampaa** [comment]
@niallel maybe you have an older version of the plugin?

**Comment by niallel** [comment]
I'd installed the one from npm with 

`cordova plugin add com.lampa.startapp`

I've just tried with installing from git with
`cordova plugin add https://github.com/lampaa/com.lampa.startapp.git`

and it works!!!!

The only thing is the version still shows as 0.14 - same as the one from npm.

Thanks for the help, its much appreciated.

**Comment by lampaa** [comment]
@niallel hmm, thanks for the report, I'll definitely check this in the next version.
